version: '3.8'

services:
  api:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
      - CLICKHOUSE_URL=clickhouse://default:@clickhouse:9000/analytics
    deploy:
      replicas: 4
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - clickhouse

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    ports:
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data:
